name: Integration

on:
  push:
    paths:
    - "*"
    - "!README.md"
    - "!.dockerignore"
    - "!.gitignore"
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.x'
      - name: Vet
        run: make vet
      - name: Test
        run: make coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.x'
      - name: Build
        run: make build

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker
        run: make docker
